[package]
name    = "bmrf"
version = "0.0.1"
authors = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
edition = "2024"

[dependencies]

[target.x86_64-unknown-linux-gnu.dependencies]

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
panic-semihosting = "0.6.0"

[[bin]]
name  = "bmrf"
path  = "src/bmrf.rs"
test  = false
bench = false

[features]

# hw
## hw/x86
pc              = ["i5"]
## hw/stm32
netduinoplus2   = ["stm32f405rg"]
iskra           = ["stm32f405rg"]
f4disco         = ["stm32f407vg"]
f429disco       = ["stm32f429zi"]
pillF103        = ["stm32f103"]
## hw/esp
esp8266         = ["xtensa","rtos8266"]
esp32           = ["xtensa","idf"]

# cpu
## cpu/x86
i5              = ["x86_64"]
i486            = ["i386"]
i686            = ["i386"]
## cpu/stm32
stm32f103       = ["stm32f1"]
stm32f405rg     = ["stm32f4"]
stm32f407vg     = ["stm32f4"]
stm32f429zi     = ["stm32f4"]
# series
stm32f1         = ["cortexM"]
stm32f4         = ["cortexM"]
# arch
x86_64          = ["linux"]
i386            = ["linux"]
cortexM         = ["bare"]
xtensa          = []

# os
linux           = []
mingw           = []
bare            = []
rtos8266        = []
idf             = []
